In [1]:
#Arrays 1D

import numpy as np

# declaração de um array (vetor)
vet = np.array([0,1,2,3,4,5,6,7,8,9])
print(vet)

#propriedades
print(vet.ndim)
print(vet.size)
print(vet.dtype.name)

#indexação
print(vet[5])         #elemento do índice 5
print(vet[1:4])       #elementos do índice 1 até o índice < 4
print(vet[0:10:2])    #elementos do índice 0 até 10 de 2 em 2
print(vet[6:])        #elementos do índice 6 até o final
print(vet[-1])        #último elemento do vetor

#funções básicas
print(vet.sum())
print(np.sum(vet))
print(vet.min())      # menor valor
print(vet.max())      # maior valor
print(vet.mean())     # média
print(vet.std())      # desvio padrão


[0 1 2 3 4 5 6 7 8 9]
1
10
int32
5
[1 2 3]
[0 2 4 6 8]
[6 7 8 9]
9
45
45
0
9
4.5
2.8722813232690143


In [ ]:
import numpy as networkx.ipynb
mat = np.zeros((5,5), dtype = nb.float)

mat = np.ones((3,5), dtype = np.int)*-1

mat = np.arange(0,100,5)
mat = mat.reshape(4,5)

mat = np.linspace(0.0,1.0,20)

mat = np.random.rand(5,5)

mat = np.random.randint(1, 61, size = 6)

mat = np.random.randint(1, 100, size=(5,5))

m1 = np.arange(9).reshape(3,3)
m2 = np.linspace(1, 20, 9).reshape(3,3)
print(m1)
print(m2)

m3 = m1 + m2
m3 = m1 - m2
m3 = m1 * 5